image: registry.gitlab.com/eqsoft/bootlinux-docker:stretch

build:
        script: ./build.sh
        when: manual
        artifacts:
            name: "filesystem_$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
            paths: 
                - binary/live/filesystem.squashfs
                - binary/live/initrd.img
                - binary/live/vmlinuz
                - binary/live/username
