#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

set -e

exit 0

. /etc/environment

OverlayProfile ()
{
    mkdir -p /home/${username}/.config/chromium
    mkdir /tmp/workdir
    mkdir /tmp/upperdir
    mount -t overlay -o lowerdir=${xnfsmount}/dev/seb3/chromium-userdata,upperdir=/tmp/upperdir,workdir=/tmp/workdir none /home/${username}/.config/chromium
    chown -R ${username}.${username} /home/${username}/.config/chromium
}

OverlayProfile
